use crate::config;
use crate::skills::Skill;
use std::collections::HashMap;
use std::fs;

pub struct AgentsMdGenerator;

impl AgentsMdGenerator {
    pub fn generate(skills: &HashMap<String, Skill>) -> Result<String, String> {
        let mut content = String::new();

        content.push_str("# Agent Instructions\n\n");
        content.push_str("This file is auto-generated by smart-skills. Do not edit manually.\n\n");

        let mut sorted_skills: Vec<_> = skills.values().collect();
        sorted_skills.sort_by(|a, b| a.name.cmp(&b.name));

        for skill in sorted_skills {
            content.push_str(&format!("## {}\n\n", skill.name));
            content.push_str(&skill.content);
            content.push_str("\n\n---\n\n");
        }

        Ok(content)
    }

    pub fn write(skills: &HashMap<String, Skill>) -> Result<(), String> {
        let content = Self::generate(skills)?;
        fs::write(config::agents_md_path(), content).map_err(|e| e.to_string())?;
        Ok(())
    }
}
